kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pvc
  namespace: mywp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi-nas1